# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f4e1c21558580964f9fedbfccd62b97a1c423d1ab6d7b69f374d604605943ef774530bc2c806e39fc5d0aed5c045b1dfde9fd14b3a57acb7b948316f61c3573

test:
  secret_key_base: 0bea199a660866bc404e21452227935ea50b9313a9b24f5222207f1bfebf48bd85611929f3b0863daf29c93f66134b121f85765f25a2f5168fdbf086d686d075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
